# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-11 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_auto_20190207_0112'),
        ('blog', '0005_auto_20190211_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('blogarticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogArticle', verbose_name='博客文章id')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.CommentsModel', verbose_name='评论的id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserModel', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '博客评论管理',
                'verbose_name_plural': '博客评论管理',
            },
        ),
    ]
