# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-06 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('blog_title', models.CharField(max_length=200, verbose_name='博客标题')),
                ('blog_content', models.TextField(verbose_name='博客内容')),
                ('blog_status', models.SmallIntegerField(choices=[(1, '0积分'), (2, '20积分'), (3, '30积分'), (4, '50积分')], default=1, verbose_name='博客权限')),
                ('blog_is_publish', models.BooleanField(choices=[(True, '发表'), (False, '未发表')], default=False, verbose_name='博客状态')),
            ],
            options={
                'verbose_name': '博客文章管理',
                'verbose_name_plural': '博客文章管理',
            },
        ),
        migrations.CreateModel(
            name='BlogClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('class_name', models.CharField(max_length=100, verbose_name='博客文章分类名称')),
            ],
            options={
                'verbose_name': '博客文章分类管理',
                'verbose_name_plural': '博客文章分类管理',
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('tag_name', models.CharField(max_length=100, verbose_name='标签名称')),
            ],
            options={
                'verbose_name': '博客标签管理',
                'verbose_name_plural': '博客标签管理',
            },
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='blogclassify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogClassify', verbose_name='博客分类id'),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='blogtag',
            field=models.ManyToManyField(to='blog.BlogTag', verbose_name='博客标签'),
        ),
    ]
