# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-06 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('carousel_name', models.CharField(max_length=200, verbose_name='轮播名称')),
                ('img_url', models.ImageField(upload_to='carousel/%Y%m/%d', verbose_name='轮播图片地址')),
                ('order', models.SmallIntegerField(default=0, verbose_name='轮播图片排序')),
                ('blogarticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogArticle', verbose_name='博客文章')),
            ],
            options={
                'verbose_name': '轮播管理',
                'verbose_name_plural': '轮播管理',
            },
        ),
    ]
