# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 01:12
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_carousel_show_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='blog_img',
            field=models.ImageField(blank=True, null=True, upload_to='blogarticle/%Y%m/%d'),
        ),
        migrations.AlterField(
            model_name='blogarticle',
            name='blog_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='博客内容'),
        ),
    ]
