# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-11 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190207_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='blog_img',
            field=models.ImageField(blank=True, null=True, upload_to='blogarticle/%Y%m/%d', verbose_name='博客图片地址'),
        ),
    ]
