# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-17 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190211_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='blog_brief',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, verbose_name='博客摘要'),
            preserve_default=False,
        ),
    ]
