# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-04 09:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^1[3-9]d{9}', '手机号码格式不正确!')], verbose_name='粉丝手机号码')),
                ('password', models.CharField(max_length=64, verbose_name='粉丝密码')),
                ('nickname', models.CharField(blank=True, default=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^1[3-9]d{9}', '手机号码格式不正确!')], verbose_name='粉丝手机号码'), max_length=100, null=True, verbose_name='粉丝昵称')),
                ('sex', models.SmallIntegerField(choices=[(1, '男'), (2, '女'), (3, '保密')], default=3, verbose_name='粉丝性别')),
                ('user_status', models.SmallIntegerField(choices=[(1, '正常'), (2, '禁言'), (3, '禁止登陆')], default=1, verbose_name='粉丝状态')),
            ],
            options={
                'verbose_name': '粉丝管理',
                'verbose_name_plural': '粉丝管理',
                'db_table': 'user',
            },
        ),
    ]
