# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-05 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='粉丝昵称'),
        ),
    ]
