# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-06 00:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('user', '0002_auto_20190205_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_buyblogarticle',
            field=models.ManyToManyField(to='blog.BlogArticle', verbose_name='用户购买博客文章'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_integral',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=9, verbose_name='用户积分'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='用户昵称'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=64, verbose_name='用户密码'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}', '手机号码格式不正确!')], verbose_name='用户手机号码'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='sex',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女'), (3, '保密')], default=3, verbose_name='用户性别'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_status',
            field=models.SmallIntegerField(choices=[(1, '正常'), (2, '禁止评论'), (3, '禁止登陆')], default=1, verbose_name='用户状态'),
        ),
    ]
