# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-20 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190207_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='head',
            field=models.ImageField(default='head/avatar.jpg', upload_to='head/%Y%m/%d', verbose_name='用户头像'),
        ),
    ]
