# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-20 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_usermodel_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='nickname',
            field=models.CharField(default='莫言', max_length=100, verbose_name='用户昵称'),
        ),
    ]
