# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-24 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190220_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('content', models.TextField(verbose_name='留言内容')),
                ('parent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.BoardModel', verbose_name='留言id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserModel', verbose_name='留言用户id')),
            ],
            options={
                'verbose_name': '用户留言管理',
                'verbose_name_plural': '用户留言管理',
            },
        ),
    ]
